// Generated by CoffeeScript 1.6.3
$(function() {
  var News, get_article, marked_settings, news_temp_html, template, url;
  News = Parse.Object.extend("News");
  news_temp_html = $("#full_article_template").html();
  template = Handlebars.compile(news_temp_html);
  marked_settings = {
    gfm: true,
    tables: true,
    breaks: true,
    smartypants: true
  };
  get_article = function(article_id) {
    var query;
    query = new Parse.Query(News);
    return query.get(article_id).then(function(article) {
      return (function(article) {
        var code_kind, md_body, md_body_snippet, md_title, new_article, new_article_txt, _ref, _ref1, _ref2;
        md_body = marked(article.get("body"));
        md_body_snippet = md_body;
        md_title = $(marked(article.get("title"))).html();
        new_article_txt = template({
          title: md_title,
          icon: (_ref = article.get("icon")) != null ? _ref : "fa fa-code",
          "class": "full-article",
          image: article.get("image"),
          body: md_body,
          body_snippet: md_body_snippet,
          width: (_ref1 = article.get("width")) != null ? _ref1 : 12,
          pubdate: moment(article.get("pubdate")).format("L LT"),
          ago: moment(article.get("pubdate")).fromNow()
        });
        new_article = $(new_article_txt).first().appendTo("#article");
        if (article.get("code") || new_article.find(/<code>/i)) {
          code_kind = (_ref2 = article.get("code")) != null ? _ref2 : "coffeescript";
          new_article.find('pre').addClass("prettyprint");
          prettyPrint(new_article[0]);
        }
        if (article.get("image")) {
          new_article.addClass("with-photo").find(".bk-image").css("background-image", "url('" + (article.get("image")) + "')");
        }
        return $.attach_focus_events(new_article[0]);
      })(article);
    });
  };
  url = $.url();
  return get_article(url.param("id"));
});

/*
//@ sourceMappingURL=article.map
*/
