// Generated by CoffeeScript 1.6.3
$(function() {
  var News, get_news, marked_settings, news_temp_html, template, url;
  Parse.initialize("AVv5O6z1eS96ZO5rnMRecr1x4L0JUASLlUefmZ7m", "fjpd9F6ECYZMvbqETnX6sCajCoKF4Q1fabWq9Rru");
  News = Parse.Object.extend("News");
  news_temp_html = $("#article_template").html();
  template = Handlebars.compile(news_temp_html);
  marked_settings = {
    gfm: true,
    tables: true,
    breaks: true,
    smartypants: true
  };
  get_news = function(page) {
    var query;
    if (page == null) {
      page = 0;
    }
    query = new Parse.Query(News).limit(25).skip(page * 25).equalTo("published", true).descending("pubdate");
    return query.find().then(function(news) {
      var article, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = news.length; _i < _len; _i++) {
        article = news[_i];
        _results.push((function(article) {
          var code_kind, md_body, md_body_snippet, md_title, new_article, on_exit, on_hover, _ref, _ref1, _ref2;
          md_body = marked(article.get("body"));
          md_body_snippet = marked((_ref = article.get("body_snippet")) != null ? _ref : _.str.prune(article.get("body"), 144));
          md_title = $(marked(article.get("title"))).html();
          new_article = template({
            title: md_title,
            image: article.get("image"),
            body: md_body,
            body_snippet: md_body_snippet,
            width: (_ref1 = article.get("width")) != null ? _ref1 : 12,
            pubdate: moment(article.get("pubdate")).format("L LT"),
            ago: moment(article.get("pubdate")).fromNow()
          });
          on_hover = function() {
            return $("body").addClass("reading");
          };
          on_exit = function() {
            return $("body").removeClass("reading");
          };
          new_article = $(new_article).appendTo("#articles").children("article").hover(on_hover, on_exit);
          if (article.get("code") || new_article.find(/<code>/i)) {
            code_kind = (_ref2 = article.get("code")) != null ? _ref2 : "coffeescript";
            new_article.find('pre').addClass("prettyprint");
            prettyPrint(new_article[0]);
          }
          if (article.get("image")) {
            return new_article.addClass("with-photo").find(".bk-image").css("background-image", "url('" + (article.get("image")) + "')");
          }
        })(article));
      }
      return _results;
    });
  };
  url = $.url();
  return get_news(url.param("page"));
});

/*
//@ sourceMappingURL=home.map
*/
